# # This is a basic workflow to help you get started with Actions

# name: CI

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     container: pandoc/latex
#     steps:
#       - uses: actions/checkout@v2
#       - name: creates output
#         run:  sh ./build.sh
#       - name: Pushes to another repository
#         uses: rnurdinb/System@master
#         env:
#           API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
#         with:
#           source-directory: 'output'
#           destination-github-username: 'rnurdinb'
#           destination-repository-name: 'knowledge-base'
#           user-email: nurdin@alterra.id
